[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "log_analyzer"
version = "0.1.0"
description = "Django Log Analyzer"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pytest=8.3.5"
]